### ISSUE TITLE
Can't create  `/sdcard/screenshots` due to  Scoped Storage in API31

### ISSUE THREAD

**Issue by aya2453** [firebase/firebase-testlab-instr-lib#16]
`FirebaseScreenCaptureProcessor` can't create `/sdcard/screenshots` in API31.

I want to run instrumentation tests on Firebase Test Lab, so [this solution](https://github.com/firebase/firebase-testlab-instr-lib/issues/7#issuecomment-1109007746) doesn't work.

**Comment by thatfiredev** [comment]
@aya2453 I see you closed this issue. Did you manage to fix it?
It might be worth posting the solution here as it will help developers who encounter the same issue in the future :)

**Comment by aya2453** [comment]
@thatfiredev 
No, I gave up using Firebase Test Lab 😢
